### ISSUE TITLE
extends: duplicate `require` throws

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/boats-utils#6]
model.yaml
```yaml
type: object
required:
 - key
properties:
  key:
    type: string
```

post.yaml
and extends:
```yaml
{{ extend('./model.yaml', { require: ['properties.key'] } ) }}
```

throws because required is array of ["key", "key"]
